apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: jonah-service
  description: Hello World example for gRPC
spec:
  type: grpc
  lifecycle: deprecated
  owner: grpc@example.com
  definition: |
    syntax = "proto3";
    option java_package = "com.example.jonahservice.proto";
    service Greeter {
        rpc SayHello ( HelloRequest) returns (  HelloReply) {}
    }
    // The request message containing the user's name.
    message HelloRequest {
        string name = 1;
    }
    // The response message containing the greetings
    message HelloReply {
        string message = 1;
    }
