apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: jonah-service
  description: Hello World example for gRPC
  annotations:
    backstage.io/definition-at-location: "https://github.com/backjo/jonah-service/blob/master/src/main/resources/greeter.proto"
spec:
  type: grpc
  lifecycle: deprecated
  owner: grpc@example.com
  implementsApis:
  - jonah-service
